name: Action Sample

run-name: pull_request

on:
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Lint Check
        run: yarn --cwd frontend/ run lint

      - name: Type Check
        run: yarn --cwd frontend/ run tsc
