name: TypeScript and ESLint Check
on:
  pull_request:
    types: opened
    paths: 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: yarn
      - name: Run TypeScript Check
        run: yarn tsc
      - name: Run ESLint Check
        run: yarn lint
