name: Action Sample

run-name: test

on:
  push:
    paths:
      - src/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Lint Check
        run: yarn --cwd src/ run lint

      - name: Type Check
        run: yarn --cwd src/ run tsc
