name: Action Sample

run-name: pull_request

on:
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: yarn ci
        run: |
          yarn tsc
          yarn lint
        working-directory: ./src
